<?php

namespace Database\Seeders;

use App\Models\AssetType;
use Illuminate\Database\Seeder;

class AssetTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get or create a default user for seeding
        $user = \App\Models\User::first();
        if (! $user) {
            $user = \App\Models\User::create([
                'name' => 'System Admin',
                'email' => 'admin@system.local',
                'password' => bcrypt('password'),
            ]);
        }

        // Get or create a default team
        $team = \App\Models\Team::first();
        if (! $team) {
            $team = \App\Models\Team::create([
                'name' => 'Default Team',
                'description' => 'System default team',
                'owner_id' => $user->id,
                'is_active' => true,
                'created_by' => $user->id,
                'updated_by' => $user->id,
                'created_checksum' => hash('sha256', 'default_team_created'),
                'updated_checksum' => hash('sha256', 'default_team_updated'),
            ]);
        }

        $assetTypes = [
            // Investment Funds
            [
                'type' => 'equityfund',
                'name' => 'Aksjefond',
                'description' => 'Aksjefond eller fond som det kalles på, populært',
                'category' => 'Investment Funds',
                'icon' => 'heroicon-o-chart-bar',
                'color' => 'success',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 1,
            ],
            [
                'type' => 'bondfund',
                'name' => 'Rentefond',
                'description' => 'Rentefond - mutual funds investing primarily in bonds',
                'category' => 'Investment Funds',
                'icon' => 'heroicon-o-banknotes',
                'color' => 'success',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 2,
            ],
            [
                'type' => 'mixedfund',
                'name' => 'Kombinasjonsfond',
                'description' => 'Kombinasjonsfond - balanced funds with both stocks and bonds',
                'category' => 'Investment Funds',
                'icon' => 'heroicon-o-scale',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 3,
            ],
            [
                'type' => 'indexfund',
                'name' => 'Indeksfond',
                'description' => 'Indeksfond - passive funds tracking market indices',
                'category' => 'Investment Funds',
                'icon' => 'heroicon-o-chart-pie',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 4,
            ],
            [
                'type' => 'hedgefund',
                'name' => 'Hedgefond',
                'description' => 'Hedgefond - alternative investment funds with flexible strategies',
                'category' => 'Investment Funds',
                'icon' => 'heroicon-o-shield-exclamation',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 5,
            ],

            // Securities
            [
                'type' => 'stock',
                'name' => 'Aksjer',
                'description' => 'Aksjer. Må hensynta fritaksregelen. Ingen skatt på salg av aksjer fra et firma, kun skatt ved salg av aksjer for privatpersoner',
                'category' => 'Securities',
                'icon' => 'heroicon-o-building-office',
                'color' => 'info',
                'is_active' => true,
                'is_private' => true,
                'is_company' => true,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 6,
            ],
            [
                'type' => 'ask',
                'name' => 'Aksjesparing med skattefradrag',
                'description' => 'Aksjesparing med skattefradrag - tax-advantaged stock savings account',
                'category' => 'Securities',
                'icon' => 'heroicon-o-receipt-percent',
                'color' => 'warning',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => true,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 7,
            ],
            [
                'type' => 'bonds',
                'name' => 'Obligasjoner',
                'description' => 'Obligasjoner - individual government and corporate bonds',
                'category' => 'Securities',
                'icon' => 'heroicon-o-document-text',
                'is_active' => true,
                'is_private' => true,
                'is_company' => true,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 8,
            ],
            [
                'type' => 'options',
                'name' => 'Opsjoner',
                'description' => 'Opsjoner - financial derivatives giving rights to buy/sell assets',
                'category' => 'Securities',
                'icon' => 'heroicon-o-arrow-path',
                'is_active' => true,
                'is_private' => true,
                'is_company' => true,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 9,
            ],
            [
                'type' => 'warrants',
                'name' => 'Warranter',
                'description' => 'Warranter - long-term options issued by companies',
                'category' => 'Securities',
                'icon' => 'heroicon-o-ticket',
                'is_active' => true,
                'is_private' => true,
                'is_company' => true,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 10,
            ],

            // Cash & Banking
            [
                'type' => 'bank',
                'name' => 'Bankkonto',
                'description' => 'Bankkonto - regular bank account deposits',
                'category' => 'Cash Equivalents',
                'icon' => 'heroicon-o-building-library',
                'is_active' => true,
                'is_private' => true,
                'is_company' => true,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 11,
            ],
            [
                'type' => 'cash',
                'name' => 'Kontanter',
                'description' => 'Kontanter - physical cash and immediate liquidity',
                'category' => 'Cash Equivalents',
                'icon' => 'heroicon-o-currency-dollar',
                'is_active' => true,
                'is_private' => true,
                'is_company' => true,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 12,
            ],
            [
                'type' => 'savings',
                'name' => 'Sparekonto',
                'description' => 'Sparekonto - high-yield savings account',
                'category' => 'Cash Equivalents',
                'icon' => 'heroicon-o-banknotes',
                'is_active' => true,
                'is_private' => true,
                'is_company' => true,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 13,
            ],
            [
                'type' => 'timedeposit',
                'name' => 'Tidsinnskudd',
                'description' => 'Tidsinnskudd - fixed-term deposit with guaranteed interest',
                'category' => 'Cash Equivalents',
                'icon' => 'heroicon-o-clock',
                'is_active' => true,
                'is_private' => true,
                'is_company' => true,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 14,
            ],
            [
                'type' => 'moneymarket',
                'name' => 'Pengemarkedsfond',
                'description' => 'Pengemarkedsfond - money market mutual funds',
                'category' => 'Cash Equivalents',
                'icon' => 'heroicon-o-circle-stack',
                'is_active' => true,
                'is_private' => true,
                'is_company' => true,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 15,
            ],

            // Vehicles & Personal Assets
            [
                'type' => 'car',
                'name' => 'Bil',
                'description' => 'Bil - personal vehicle',
                'category' => 'Personal Assets',
                'icon' => 'heroicon-o-truck',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => false,
                'can_generate_expenses' => true,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => false,
                'sort_order' => 16,
            ],
            [
                'type' => 'boat',
                'name' => 'Båt',
                'description' => 'Båt - boat or watercraft',
                'category' => 'Personal Assets',
                'icon' => 'heroicon-o-paper-airplane',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => false,
                'can_generate_expenses' => true,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => false,
                'sort_order' => 17,
            ],
            [
                'type' => 'jewelry',
                'name' => 'Smykker',
                'description' => 'Smykker - jewelry and precious items',
                'category' => 'Personal Assets',
                'icon' => 'heroicon-o-star',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => false,
                'can_generate_expenses' => true,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => false,
                'sort_order' => 18,
            ],
            [
                'type' => 'furniture',
                'name' => 'Møbler',
                'description' => 'Møbler - furniture and household items',
                'category' => 'Personal Assets',
                'icon' => 'heroicon-o-home',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => false,
                'can_generate_expenses' => true,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => false,
                'sort_order' => 19,
            ],

            // Alternative Investments
            [
                'type' => 'crypto',
                'name' => 'Krypto',
                'description' => 'Krypto - digital currencies and crypto assets',
                'category' => 'Alternative Investments',
                'icon' => 'heroicon-o-computer-desktop',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => false,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 20,
            ],
            [
                'type' => 'gold',
                'name' => 'Gull',
                'description' => 'Gull - physical gold and precious metals',
                'category' => 'Alternative Investments',
                'icon' => 'heroicon-o-star',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => false,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 21,
            ],

            // Tax Optimized Assets
            [
                'type' => 'ips',
                'name' => 'Pensjonssparing (IPS)',
                'description' => 'Pensjonssparing med spesielle skatteregler.',
                'category' => 'Pension & Retirement',
                'icon' => 'heroicon-o-academic-cap',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => true,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 22,
            ],
            [
                'type' => 'endowment',
                'name' => 'Kapitalforsikring',
                'description' => 'Kapitalforsikring - endowment insurance for tax-efficient savings',
                'category' => 'Insurance & Protection',
                'icon' => 'heroicon-o-shield-exclamation',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => true,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => false,
                'sort_order' => 23,
            ],

            // Real Estate & Property
            [
                'type' => 'house',
                'name' => 'Bolig',
                'description' => 'Primærbolig eller sekundærbolig',
                'category' => 'Real Assets',
                'icon' => 'heroicon-o-home',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => false,
                'can_generate_expenses' => true,
                'can_have_mortgage' => true,
                'can_have_market_value' => true,
                'is_fire_sellable' => false,
                'sort_order' => 24,
            ],
            [
                'type' => 'rental',
                'name' => 'Utleieeiendom',
                'description' => 'Eiendom for utleie og inntektsgenerering',
                'category' => 'Real Assets',
                'icon' => 'heroicon-o-building-office',
                'is_active' => true,
                'is_private' => true,
                'is_company' => true,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => true,
                'can_have_mortgage' => true,
                'can_have_market_value' => true,
                'is_fire_sellable' => false,
                'sort_order' => 25,
            ],
            [
                'type' => 'cabin',
                'name' => 'Hytte',
                'description' => 'Fritidsbolig eller hytte',
                'category' => 'Real Assets',
                'icon' => 'heroicon-o-home',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => false,
                'can_generate_expenses' => true,
                'can_have_mortgage' => true,
                'can_have_market_value' => true,
                'is_fire_sellable' => false,
                'sort_order' => 26,
            ],

            // Income & Employment
            [
                'type' => 'salary',
                'name' => 'Lønn',
                'description' => 'Lønnsinntekt fra arbeidsgiver',
                'category' => 'Income',
                'icon' => 'heroicon-o-briefcase',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => false,
                'is_fire_sellable' => false,
                'sort_order' => 27,
            ],
            [
                'type' => 'income',
                'name' => 'Annen inntekt',
                'description' => 'Diverse inntektskilder',
                'category' => 'Income',
                'icon' => 'heroicon-o-banknotes',
                'is_active' => true,
                'is_private' => true,
                'is_company' => true,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => false,
                'is_fire_sellable' => false,
                'sort_order' => 28,
            ],

            // Pension & Retirement
            [
                'type' => 'pension',
                'name' => 'Pensjon',
                'description' => 'Offentlig pensjon og pensjonsutbetalinger',
                'category' => 'Pension & Retirement',
                'icon' => 'heroicon-o-shield-check',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => false,
                'is_fire_sellable' => false,
                'sort_order' => 29,
            ],
            [
                'type' => 'otp',
                'name' => 'Tjenestepensjon (OTP)',
                'description' => 'Obligatorisk tjenestepensjon fra arbeidsgiver',
                'category' => 'Pension & Retirement',
                'icon' => 'heroicon-o-shield-check',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => true,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => false,
                'is_fire_sellable' => false,
                'sort_order' => 30,
            ],

            // Family & Social Benefits
            [
                'type' => 'child',
                'name' => 'Barnetrygd',
                'description' => 'Barnetrygd og andre familieytelser',
                'category' => 'Social Benefits',
                'icon' => 'heroicon-o-user',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => false,
                'is_fire_sellable' => false,
                'sort_order' => 31,
            ],
            [
                'type' => 'inheritance',
                'name' => 'Arv',
                'description' => 'Arv og gaver',
                'category' => 'Transfers',
                'icon' => 'heroicon-o-gift',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => false,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => false,
                'is_fire_sellable' => false,
                'sort_order' => 32,
            ],

            // Business & Company
            [
                'type' => 'company',
                'name' => 'Selskap',
                'description' => 'Eierandel i selskap eller bedrift',
                'category' => 'Business',
                'icon' => 'heroicon-o-building-office',
                'is_active' => true,
                'is_private' => false,
                'is_company' => true,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => true,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => false,
                'sort_order' => 33,
            ],

            // Technology & Consumer Goods
            [
                'type' => 'iphone',
                'name' => 'iPhone',
                'description' => 'iPhone og andre teknologiprodukter',
                'category' => 'Consumer Goods',
                'icon' => 'heroicon-o-device-phone-mobile',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => false,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => false,
                'sort_order' => 34,
            ],
            [
                'type' => 'applestock',
                'name' => 'Apple-aksjer',
                'description' => 'Apple Inc. aksjer',
                'category' => 'Securities',
                'icon' => 'heroicon-o-building-office',
                'is_active' => true,
                'is_private' => true,
                'is_company' => true,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => true,
                'is_fire_sellable' => true,
                'sort_order' => 35,
            ],

            // Test & Development
            [
                'type' => 'test',
                'name' => 'Test',
                'description' => 'Test asset type for development and validation',
                'category' => 'Development',
                'icon' => 'heroicon-o-beaker',
                'is_active' => true,
                'is_private' => true,
                'is_company' => true,
                'is_tax_optimized' => false,
                'can_generate_income' => false,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => false,
                'is_fire_sellable' => false,
                'sort_order' => 36,
            ],
            [
                'type' => 'kpi',
                'name' => 'KPI',
                'description' => 'Consumer Price Index tracking asset',
                'category' => 'Development',
                'icon' => 'heroicon-o-chart-pie',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => false,
                'can_generate_expenses' => false,
                'can_have_mortgage' => false,
                'can_have_market_value' => false,
                'is_fire_sellable' => false,
                'sort_order' => 37,
            ],

            // Special Categories
            [
                'type' => 'spouse',
                'name' => 'Ektefelle',
                'description' => 'Ektefelles inntekt og utgifter',
                'category' => 'Family',
                'icon' => 'heroicon-o-user',
                'is_active' => true,
                'is_private' => true,
                'is_company' => false,
                'is_tax_optimized' => false,
                'can_generate_income' => true,
                'can_generate_expenses' => true,
                'can_have_mortgage' => false,
                'can_have_market_value' => false,
                'is_fire_sellable' => false,
                'sort_order' => 38,
            ],
        ];

        foreach ($assetTypes as $assetType) {
            // All capability flags are now defined directly in the array structure above
            // No logic needed here - just use the values as-is
            $code = $assetType['type'];
            $cat = $assetType['category'] ?? null;

            // Stamp required ownership & audit fields
            $assetType['user_id'] = $user->id;
            $assetType['team_id'] = $team->id;
            $assetType['created_by'] = $user->id;
            $assetType['updated_by'] = $user->id;
            $assetType['created_checksum'] = $assetType['created_checksum'] ?? hash('sha256', 'asset_type_created_'.$code);
            $assetType['updated_checksum'] = $assetType['updated_checksum'] ?? hash('sha256', 'asset_type_updated_'.$code);

            // Determine most probable tax type by category/code
            $taxCode = match ($cat) {
                'Cash Equivalents' => 'income',
                'Real Assets' => 'property',
                'Personal Assets' => 'fortune',
                'Pension & Retirement' => 'income',
                'Insurance & Protection' => 'realization',
                'Investment Funds', 'Securities', 'Alternative Investments' => 'realization',
                default => 'income',
            };

            // Specific overrides by code
            if (in_array($code, ['bonds'], true)) {
                $taxCode = 'income';
            }

            // Lookup tax type id
            $taxTypeId = \App\Models\TaxType::where('type', $taxCode)->value('id');
            if ($taxTypeId) {
                $assetType['tax_type_id'] = $taxTypeId;
            }

            AssetType::updateOrCreate(
                ['type' => $assetType['type']],
                $assetType
            );
        }
    }
}
